---
title: "Hands-on Exercise 2"
author: "Cheryl Jeanne Chiew"
date: "`r Sys.Date()`"
---

# Getting Started

## Installing and launching R packages

```{r}
pacman::p_load(tidyverse, patchwork, 
               ggthemes, hrbrthemes,
               ggrepel) 
```

## Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

# Ggrepel for Scatterplot Charts

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  geom_label_repel(aes(label = ID), 
                   fontface = "bold") +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English scores versus Maths scores for Primary 3")
```

# Using Ggplot Themes I

```{r}
ggplot(data=exam_data, 
             aes(x = MATHS)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") +
  theme_gray() +  
  ggtitle("Distribution of Maths scores") 
```

# Using Ggplot Themes II

```{r}
ggplot(data=exam_data, 
             aes(x = MATHS)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") +
  ggtitle("Distribution of Maths scores") +
  theme_economist()
```

# Using HRBTHEMS Package

```{r}
ggplot(data=exam_data, 
             aes(x = MATHS)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") +
  ggtitle("Distribution of Maths scores") +
  theme_ipsum(axis_title_size = 18, 
              base_size = 15, 
              grid = "Y") 
```

# Creating Composite Plots by Combining Graphs with Patchwork Package

```{r}
p1 <- ggplot(data=exam_data, 
             aes(x = MATHS)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") + 
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")

p2 <- ggplot(data=exam_data, 
             aes(x = ENGLISH)) +
  geom_histogram(bins=20, 
                 boundary = 100,
                 color="grey25", 
                 fill="grey90") +
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p3 <- ggplot(data=exam_data, 
             aes(x= MATHS, 
                 y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English scores versus Maths scores for Primary 3")

#fixed positioning of plots
#(p1 / p2) | p3 
#or p1 + p2 / p3 to determine the layout

#patchwork with theme
patchwork <- (p1 / p2) | p3
patchwork & theme_economist()

#floating positioning of another plot in a plot
#p3 + inset_element(p2, 
#                   left = 0.02, 
#                   bottom = 0.7, 
#                   right = 0.5, 
#                   top = 1)
```

